### ISSUE TITLE
release.js missing

### ISSUE THREAD

**Issue by zoiodelula** [grimaldello/the-crims-italian-bot-v2#1]
copy all the content of the file release.js in the clipboard (I suggest CTRL+A to select all and then CTRL+C to copy the selected text)
iam not finding this file

**Comment by grimaldello** [comment]
> copy all the content of the file release.js in the clipboard (I suggest CTRL+A to select all and then CTRL+C to copy the selected text) iam not finding this file

Hi @zoiodelula you can find it in the releases pages: [Releases Page](https://github.com/grimaldello/the-crims-italian-bot-v2/releases)

**Comment by zoiodelula** [comment]
There is some pre setup to do? I got a red dot on my screen, but not clicking on anything

**Comment by zoiodelula** [comment]
It is working, but sometimes the click doesnt perform

**Comment by zoiodelula** [comment]
Working now

**Comment by zoiodelula** [comment]
@grimaldello dont forget to accept me on discord, we can help with some adjusts

**Comment by grimaldello** [comment]
> @grimaldello dont forget to accept me on discord, we can help with some adjusts

Open new issue here on Github explaining what you want to fix or implement.

This way, me (or maybe someone else) can help with that.
