### ISSUE TITLE
Inside the club checker

### ISSUE THREAD

**Issue by zoiodelula** [grimaldello/the-crims-italian-bot-v2#10]
The bot need to check if inside the club, when we hunt, a lot of times we get the alerts to wait some secons or unknow club, an idea is:
-Try to enter in first club
-Check if inside
-If not, choose another club from the list

**Comment by grimaldello** [comment]
Fixed: https://github.com/grimaldello/the-crims-italian-bot-v2/commit/dbf2decc7be3f73ed87c3bdac378dff93f483822

Now the bot will randomly select rave for hunting instead of going always on first rave.

**Comment by grimaldello** [comment]
I misunderstood the problem and the fix above, dosen't really fix the problem (it only lower the chances that it happens)

I added a concrete fix for this.
Now the bot:

- click on Enter button rave
- if enter -> good
- else wait for 3 seconds and then try again
