### ISSUE TITLE
Attack system

### ISSUE THREAD

**Issue by zoiodelula** [grimaldello/the-crims-italian-bot-v2#14]
There is 2 problens with the attack system:
-The click button attack should be by selector,id,xpatch, not by moving the mouse by coordinates, it looks like macros
-The second one is, when you try a attack, you dont need to press exit after, the bot is attacking and fast clicking exit button

**Comment by grimaldello** [comment]
Regarding the fast click on exit after attack, it should wait a range of times defined by this setting:
```
millisecondsToWaitAfterExitRave: {
                    min: 5000,
                    max: 6000
                },
```
Did you set correctly these values?

**Comment by zoiodelula** [comment]
> Regarding the fast click on exit after attack, it should wait a range of times defined by this setting:
> 
> ```
> millisecondsToWaitAfterAssault: {
>                     min: 5000,
>                     max: 6000
>                 },
> ```
> 
> Did you set correctly these values?

I set that, but there is a problem, if you miss the attack, the bot will wait this time inside the rave, so I cant set a value to higher to avoid hits

**Comment by zoiodelula** [comment]
> in the first implementation (never published) I used the selectors to select the single assault item and to press the assault button. Unfortunately it didn't work in some cases (never figured out why), so I used a pixel offset (not a great solution but it works better)
> 
> I can implement again the mode with selectors via a strategy pattern and permits to select the strategy (offset pixel strategy or selector strategy) the bot will use with a setting.
> 
> How about instead of randomizing the pixel offset instead?

I did that, 
                        // Select Single Assault item
                        let currentPosition: DOMCoordinate = this.mouse.getFakeCursorDOMCoordinate();
                        const randomSingleAssaultX: number = Math.random() * (3 - 0) + 0;
                        const randomSingleAssaultY: number = Math.random() * (62 - 57) + 57;
                        await this.botDomHelper.moveFromCurrentCoordinateToAnotherCoordinateAndClick({
                            x: currentPosition.x + randomSingleAssaultX,
                            y: currentPosition.y + randomSingleAssaultY
                        });
                        await this.waitUtils.waitRandomMillisecondsBetween(110,280);

                        // Click Assault button
                        currentPosition = this.mouse.getFakeCursorDOMCoordinate();
                        const randomSingleAssaultX2: number = Math.random() * (3 - 0) + 0;
                        const randomSingleAssaultY2: number = Math.random() * (32 - 27) + 27;
                        await this.botDomHelper.moveFromCurrentCoordinateToAnotherCoordinateAndClick({
                            x: currentPosition.x -randomSingleAssaultX2,
                            y: currentPosition.y -randomSingleAssaultY2
                        });

I will be better if we use the max values, using like this, i miss some hits but there is no problem, it looks more human
