### ISSUE TITLE
Assault Timer

### ISSUE THREAD

**Issue by zoiodelula** [grimaldello/the-crims-italian-bot-v2#25]
its good to know the total time of each assault from the first click of the assault until the end

**Comment by grimaldello** [comment]
Hi @zoiodelula, you mean print on the browser console the amount of time (in seconds or milliseconds) that passed starting from the single assault select item, till the click of attack button?

**Comment by zoiodelula** [comment]
Yes, thats it

**Comment by grimaldello** [comment]
Ok, in the next days I will implement it.
