### ISSUE TITLE
Exit

### ISSUE THREAD

**Issue by Koles1910** [grimaldello/the-crims-italian-bot-v2#34]
hi, could you make it so that if the victim in the hunt does not meet the requirements, he immediately leaves the club because in my case, if he does not meet the requirements, sometimes before the mouse reaches the exit, I am already killed do as in the case of an attack that he attacks immediately

**Comment by grimaldello** [comment]
Hi,
there is a property you can change in order to not wait if before exit if some is alredy in rave.
Search in `release.js` file the following property:
```
millisecondsToWaitAfterEnterRaveIfVisitorInside: {
                    min: 0,
                    max: 100,
                },
```
and set max to 0.

In addition, I have to say that there are lags in the crims and they obciously influence the response time of the bot.
So it's almost impossible to always escape without being killed.

**Comment by Koles1910** [comment]
does it work on kill and rob?

**Comment by grimaldello** [comment]
No, that one is specifically for hunting (kill).

For rob (single and gang) the delays applied are the ones in rechargeEnergy
section of the bit settings.

Specifically search for: millisecondsToWaitAfterEnterRave and
millisecondsToWaitAfterEnterRaveIfVisitorInside.

Il lun 22 mag 2023, 09:40 Koles1910 ***@***.***> ha scritto:

**Comment by Koles1910** [comment]
I usually get it because the mouse won't be able to hover over the exit and I'm already attacked, could you fix it so that it instantly jumps to the exit only when there is someone in the club and they don't meet the requirements

**Comment by Koles1910** [comment]
because he gets all the time;

**Comment by grimaldello** [comment]
It ca ne be done what you are asking.

But there is a problem related to the crims anti cheat logging system.
They see that you make a "jump" with the mouse that is not possible if
hunting manually (and you get ban).

**Comment by Koles1910** [comment]
I understand, hmm, I don't know how to solve it because now I got it 3 times

**Comment by Koles1910** [comment]
and once again boom I don't know how they do it

**Comment by Koles1910** [comment]
after messing around with numberOfCoordinatesToSkip: because it can move the CPU load slowly yes

**Comment by grimaldello** [comment]
I will make some tests this evening (italian time) and see if there's bug
in the bot.

**Comment by Koles1910** [comment]
or how quickly people change in the club and miss the exit button, it stops and needs to be refreshed

**Comment by grimaldello** [comment]
Could you please open a separate issue (bug, enhancement, etc.) for each request you made in this issue?
By separating them in a new request we can track better the request.

As for your initial request for this issue, I haven't encountered any issues from the tests I've done.
If you "played" with the `numberOfCoordinatesToSkip` then you may have set values that makes the bot not working correctly.

I suggest you try again to use the bot with the default configurations, downloading the release.js file again from the github repository.

If you continue to have problems, I kindly ask you to describe precisely what is not working for you.

**Comment by Koles1910** [comment]
everything works turned out my laptop was loaded and that's why thanks for your help. I will create new topics
