### ISSUE TITLE
hiding img

### ISSUE THREAD

**Issue by Koles1910** [grimaldello/the-crims-italian-bot-v2#36]
part where to add to source code to enable disable document.querySelector('img[src*="https://static-live.thecrims.com/static/images/avatars/"]').style.display = " none"; document.querySelector('img[src*="https://static-live.thecrims.com/static/images/tc-menu-logo.png"]').style.display= 'none';

**Comment by grimaldello** [comment]
done v0.0.19

**Comment by Koles1910** [comment]
?

**Comment by grimaldello** [comment]
The request has been implemented in the new `release.js` file with version 0.0.19.
You can find it in the [Releases page](https://github.com/grimaldello/the-crims-italian-bot-v2/releases)

**Comment by Koles1910** [comment]
I downloaded release.js and it doesn't work, i.e. it doesn't hide images

**Comment by grimaldello** [comment]
Just tried and it's working in my case.

Are you sure you downloaded the correct version?
https://github.com/grimaldello/the-crims-italian-bot-v2/releases/download/v0.0.19/release.js

**Comment by Koles1910** [comment]
yes, it already works, if you could, add it to make it disappear https://static-live.thecrims.com/static/images/menu/menu-sprites.png

**Comment by grimaldello** [comment]
Yeah I can add it, but I need to make a new release.

Please collect all the images and when you have the complete list I will add them in a new version.

**Comment by Koles1910** [comment]
https://static-live.thecrims.com/static/images/menu/menu-sprites.png
 
 https://static-live.thecrims.com/static/images/sections/raveparty/raveparty.jpg(picture of the club so after leaving and entering you can be refreshed and show up you need to check)

**Comment by grimaldello** [comment]
I think that a dynamic check for the rave party image can be implemented,
but adding that check, costs CPU time every time it's performed.
In this case it would be very useful to check how much is the increase of
speed by deleting the image compared to CPU time needed to remove the image.

In addition, images usually are cached by browser so the only improvement
in speed, by deleting the image is the rendering time of the DOM.

**Comment by Koles1910** [comment]
I tried to add images to the source, the generation ends with success, but after pasting to the console, it crashes and the script does not work

**Comment by grimaldello** [comment]
the first line of the error, says that the selector string you used in querySelector doesn't match anything  (or this is what I understand from that log).

I suggest you to try it in the console browser directly and see if it works before put it in the bot source.

**Comment by Koles1910** [comment]
the point is that this link does not match https://static-live.thecrims.com/static/images/menu/menu-sprites.png because in the source there is backgrond-image static/images/menu/menu-sprites.png but no I have no idea how to set it up

**Comment by grimaldello** [comment]
if the element is not present in the DOM you cannot hide/remove it.

If your intention is to remove the menu images, I think the best way is to use the selector by id:

`document.querySelector('div[id*="menu-sprite-assault"]').style.display='none'; `

So in the bot the string selector to add is: `'div[id*="menu-sprite-assault"]'`

For the other images of the menu, you can find the id in the source code of HTML:
![image](https://github.com/grimaldello/the-crims-italian-bot-v2/assets/9029075/1b0557f6-cc63-4ba0-b08c-0b7670810b53)

**Comment by Koles1910** [comment]
hmmm div[class*="menu-sprite"]', ?

**Comment by grimaldello** [comment]
`document.querySelectorAll('div[class="menu-sprite"]').forEach((e)=>{e.remove()}) `

But it's not suitable for how it has been implemented the bot.

For the bot you have to put one by one the selector.

**Comment by Koles1910** [comment]
just I know
