### ISSUE TITLE
hospital and prison(idea)

### ISSUE THREAD

**Issue by Koles1910** [grimaldello/the-crims-italian-bot-v2#38]
could it be done so that after going to prison or hospital he would leave it using credits or items in the configuration to set whether he should leave and whether for credits or for item

**Comment by grimaldello** [comment]
unfortunately at the moment not, because the crims auto-refresh and the bot stop.

Maybe using Greasemonkey it could be possible, but needs to add lots o logics.

An alternative is use an external tool, but also a lot of work is necessary.

**Comment by grimaldello** [comment]
closing it, since it's not possible.
