### ISSUE TITLE
Pause and resume the bot using a keyboard shortcut

### ISSUE THREAD

**Issue by Koles1910** [grimaldello/the-crims-italian-bot-v2#40]
hi, it would be nice if after starting the script by clicking shift + z - the script would pause, and by clicking shift + x resume work, the point is that when you hunt and want to check the logs of who I attacked, you have to refresh and check, and that's how it was so that you can pause click and check and then resume work and without pasting the script

**Comment by grimaldello** [comment]
Hi @Koles1910,

thank you for reporting.

Yeah this could be a great enhancement. Maybe I can put in settings the keys combination and user can customize it.

**Comment by Koles1910** [comment]
waiting for the new release :)

**Comment by grimaldello** [comment]
done in release version v0.0.20.

Read the README on main page of repo in order to understand how it works.
