### ISSUE TITLE
Hunt atack

### ISSUE THREAD

**Issue by Koles1910** [grimaldello/the-crims-italian-bot-v2#45]
it happened a few times that he chose the victim but did not click attack and then he stops and waits for the time in kkuba to drop to 0 and when he kicks out of the club then he starts hunting again

**Comment by Koles1910** [comment]
this is what happens when assault pops up in the end and I don't have time to click attack etc. it stops and waits for the time to pass in the club and when it comes out it starts again

**Comment by grimaldello** [comment]
Hi @Koles1910,
thank you for reporting.

I know why it remains in the rave after the bot "miss" the click. Somebody told me that after the attack, it is not recommended to press the exit button, this is why it remains inside rave.

I can try to add 1 second of timeout after pressing the attack button and then exits.

**Comment by Koles1910** [comment]
yesterday I played on the mouse speed on 4 and today after turning on the paw I had to set it to 15 and it moved at such a speed as yesterday on 4, it's probably my laptop's fault?

**Comment by grimaldello** [comment]
If the bot has slow down, it means that the crims admins have enable logging on your account.

You can see it under network tab of the browser for example when you make a rob, you can see a all the mouse movement and click they log.

**Comment by Koles1910** [comment]
I don't understand :( ie they are checking me? how to check it exactly?

**Comment by Koles1910** [comment]
ok I'll check tomorrow because I don't see it, I opened the network and I have something else and when will you add the lecture after missing it?

**Comment by grimaldello** [comment]
> I on ff hate you fly movements as I chose the net and only ppshows me what clicks

Sorry, I don't understand what you have write.

For the addition of timeout after missed click for assault, there are chances that I can implement it this evening.

**Comment by Koles1910** [comment]
I selected the network tab, there are no mouse movements, only what is being clicked at the moment

**Comment by Koles1910** [comment]
I managed to find it :) now I know where it is :)

**Comment by grimaldello** [comment]
In order to mitigate the waiting time after the missed click on "Attack" button, you can try to decrease this time:
```
millisecondsToWaitAfterAssault: {
    min: 6000,
    max: 7000
},
```
maybe with `min: 1000` and `max: 2000` (or even less) could solve the problem (but dunno if new one raise :) )

**Comment by Koles1910** [comment]
> Cześć@Koles1910, dziękuję za zgłoszenie.
> 
> Wiem, dlaczego pozostaje w rave po tym, jak bot „przegapi” kliknięcie. Ktoś mi powiedział, że po ataku nie zaleca się naciskania przycisku wyjścia, dlatego pozostaje w rave.
> 
> Mogę spróbować dodać 1 sekundę limitu czasu po naciśnięciu przycisku ataku, a następnie wyjściu.

in the evening you add it, if it misses, it will come out after 1 second, and if it hits, it will come out by itself

**Comment by grimaldello** [comment]
> > Cześć@Koles1910, dziękuję za zgłoszenie.
> > Wiem, dlaczego pozostaje w rave po tym, jak bot „przegapi” kliknięcie. Ktoś mi powiedział, że po ataku nie zaleca się naciskania przycisku wyjścia, dlatego pozostaje w rave.
> > Mogę spróbować dodać 1 sekundę limitu czasu po naciśnięciu przycisku ataku, a następnie wyjściu.
> 
> in the evening you add it, if it misses, it will come out after 1 second, and if it hits, it will come out by itself

No it's already in the bot that settings.
What I mean is to try with lower values of that property.

If I'm not wrong, by lowering that values, the bot, it will exit from rave after that seconds specified in the properties, both in case of a successful attack and not

**Comment by Koles1910** [comment]
you have to come up with something because they killed me, I killed and the ban went ;/

**Comment by grimaldello** [comment]
I'm sorry for what happened :(

It would be interesting to understand the reason for the ban.

I don't know if there is any other parameter they check other than mouse
logging.

**Comment by Koles1910** [comment]
it seems to me that it's because of the top killers because I escaped them more times and they definitely reported it

**Comment by victorvadl** [comment]
@grimaldello Can you explain better how can i know if they are watching me? Where can i see it? 
![image](https://github.com/grimaldello/the-crims-italian-bot-v2/assets/99365539/adedd0bd-4224-4b9a-ac8f-cef2da09e1d1)

**Comment by grimaldello** [comment]
> @grimaldello Can you explain better how can i know if they are watching me? Where can i see it? ![image](https://user-images.githubusercontent.com/99365539/243049000-adedd0bd-4224-4b9a-ac8f-cef2da09e1d1.png)

Since this question is asked me a lot of times and could be useful for anybody, I just added it in the F.A.Q. section: https://github.com/grimaldello/the-crims-italian-bot-v2#faq

**Comment by grimaldello** [comment]
Yes I'm adding a warning in the case that the account is under investigation.

But I'm not making the bot stop in this case, since the user maybe doesn't matter of this warning and can continue use the bot.
