### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by gladiatus111** [grimaldello/the-crims-italian-bot-v2#46]
Misread the guide at first, sorry :)

**Comment by grimaldello** [comment]
Hi @gladiatus111.

In the main page of the repo it is all explained.

If you want to just use the bot, please read this: https://github.com/grimaldello/the-crims-italian-bot-v2#how-to-use-the-bot.

If you want to build a custom local version of the bot, please read this: https://github.com/grimaldello/the-crims-italian-bot-v2#local-development

**Comment by grimaldello** [comment]
> Misread the guide at first, sorry :)

No problem :)

**Comment by gladiatus111** [comment]
thanks
