### ISSUE TITLE
Doesn't work when minimizing the tab

### ISSUE THREAD

**Issue by gladiatus111** [grimaldello/the-crims-italian-bot-v2#47]
Hey, I appreciate your work!
There's a little issue about minimizing the chrome tab.

For example, I start the bot, minimize or change the thecrims tab, I check the logs 10 mins later. Nothing shows up in logs, it basically stops while im not on the same screen.

Can you adjust it so that we don't need to be on the same screen/tab?

**Comment by grimaldello** [comment]
I think I can't do much from bot side.

I think it's something related to Chrome. 
Try add an exception here chrome://settings/performance (put that link in chrome search bar or find it in settings of chrome) and add "The Crims" in the "Always keep these sites active" section.

Also try in Firefox if it's the behavior is the same.

**Comment by gladiatus111** [comment]
oh alright. I realized 1 more thing. When in assault mode, i was watching how it performs and 1 guy came in to the same room with me, it took the bot so long to click on the guy that he left, after that someone else came in and killed me :D How to make it faster when someone who matches the criteria enters the room?

**Comment by grimaldello** [comment]
What you describe is a bad behavior of the bot when it misses to press the "Attack" button  (I think I'm going to fix it in the next days).

For the assault workflow, there are some delays that you can increase/decrease in the settings:
![image](https://github.com/grimaldello/the-crims-italian-bot-v2/assets/9029075/c233c74d-9629-4bdc-82dd-3ba135f662c8)
You can play with that values and tune them as your needs.
Probably by decreasing the `millisecondsToWaitAfterAssault` could partially solve this issue.

**Comment by gladiatus111** [comment]
alright thanks mate :)

**Comment by gladiatus111** [comment]
> I think I can't do much from bot side.
> 
> I think it's something related to Chrome. Try add an exception here chrome://settings/performance (put that link in chrome search bar or find it in settings of chrome) and add "The Crims" in the "Always keep these sites active" section.
> 
> Also try in Firefox if it's the behavior is the same.

I have an old script to run hunting or other stuff i used last year. I dont know where i found it but it works on minimized tab. I can share it with you if you want.

**Comment by gladiatus111** [comment]
italian bot v1 is working with minimized tab tho 😃

**Comment by grimaldello** [comment]
yes it was a great bot ☺️

The bot v1 uses a different core sets of functionality at its base that are
not blocked by browser.

The bot v2, I think is not working in background due to  this:
https://stackoverflow.com/questions/75801697/how-to-prevent-javascript-from-running-slow-on-minimized-browser-window

Maybe the workaround described in that link could work.

But honestly, you can bypass this problem by opening the bot in a incognito
window of Chrome and let the bot rum without minimize the window.
In the no-incognito window you can do other things you need.

**Comment by gladiatus111** [comment]
will try it thanks ^^
