### ISSUE TITLE
group jumps

### ISSUE THREAD

**Issue by Koles1910** [grimaldello/the-crims-italian-bot-v2#48]
on group jumps, I would do so that after joining the jump, the mouse stops and does not fly constantly and wait for the button to appear, make a jump, or accept

**Comment by Koles1910** [comment]
and every now and then she moved now that she will join the jump and the mouse will fly all over the screen in my opinion it would be better if he joined and waited for the button

**Comment by grimaldello** [comment]
Hi @Koles1910,
thank you for reporting.

If with "jump" you mean "teleport" the fake cursor from the current point to button accept, it can be done.
BUT the anti-cheat system of the crims will surely detect this and consider this behavior as a bot.

It is needed to simulate real mouse movements and clicks as accurate as possible.

**Comment by Koles1910** [comment]
ok, I can leave it :) narqzie do not check me on a new account

**Comment by Koles1910** [comment]
how will the tc team start exploring what is best to do to defend?

**Comment by grimaldello** [comment]
> how will the tc team start exploring what is best to do to defend?

I don't know exactly :)

I suppose when competing for a top (both top respect and top kills) the admins start to investigate.

But not sure about this.
