### ISSUE TITLE
Improve logs of checks for account under investigation

### ISSUE THREAD

**Issue by gladiatus111** [grimaldello/the-crims-italian-bot-v2#53]
Hi, today i tried your new release on a completely new account. Never used any scripts on it, i was playing manually and this happened at the first time i loaded the code :
![image](https://github.com/grimaldello/the-crims-italian-bot-v2/assets/134116441/ea57f8dc-fe8f-46db-8311-337dc0f12e2e)

**Comment by grimaldello** [comment]
Hi @gladiatus111,

thank you for reporting.

Based on what you reported, there's a bug in the bot. 
I think that those logs are of the old account (those values are saved in browser localstorage).

Need to make a fix.

As a workaround, you can run the following command in the console browser:
`localStorage.clear()`

then reload page.

**Comment by grimaldello** [comment]
However you can do this check in order to test if you are REALLY under investigation: https://github.com/grimaldello/the-crims-italian-bot-v2#faq

**Comment by gladiatus111** [comment]
Alright i'll check it in a minute but i use a different chrome profile for different accounts so i dont think its because of the old account am i wrong?

**Comment by grimaldello** [comment]
I don't know if a different chrome profile, use a different browser localStorage.

A better way to test this is to use an incognito window instead of a different browser profile.

However the trick with `localStorage.clear()` should work if you are not under bot investigation.

**Comment by gladiatus111** [comment]
> `localStorage.clear()`

![image](https://github.com/grimaldello/the-crims-italian-bot-v2/assets/134116441/ec48ddd2-b3c8-4a59-91c2-c6af528ddd72)

This happened, am i too dumb to understand 😄

**Comment by gladiatus111** [comment]
By the way i think there's a way to avoid the crims crew checking on you since the kill list is like that, one of these guys also had over 200 kills at the first day
![image](https://github.com/grimaldello/the-crims-italian-bot-v2/assets/134116441/45b39b87-67ab-4c36-9fbb-c9e7b297ea85)

1695 people? I didnt even see that much on raves lol

**Comment by grimaldello** [comment]
> > `localStorage.clear()`
> 
> ![image](https://user-images.githubusercontent.com/134116441/243207640-ec48ddd2-b3c8-4a59-91c2-c6af528ddd72.png)
> 
> This happened, am i too dumb to understand smile

It's correct. That function does not print anything if it is executed correctly.

**Comment by grimaldello** [comment]
> By the way i think there's a way to avoid the crims crew checking on you since the kill list is like that, one of these guys also had over 200 kills at the first day ![image](https://user-images.githubusercontent.com/134116441/243208118-45b39b87-67ab-4c36-9fbb-c9e7b297ea85.png)
> 
> 1695 people? I didnt even see that much on raves lol

Please use this discord server: https://discord.gg/4WzCZCcK
for this kind of of things.

Let's keep github only for discussing of bot issues :)

**Comment by Koles1910** [comment]
you need to send some sppsob to avoid checking by the tc team on the first day 200 kills, it was definitely a bot

**Comment by Koles1910** [comment]
maybe it is possible to make it so that if the bot is running, the system cursor disappears so that it is not visible in the log, and if we stop the bot, the cursor will appear in the same place as the false pointer
