### ISSUE TITLE
Changing cursor speed and moving mechanism

### ISSUE THREAD

**Issue by gladiatus111** [grimaldello/the-crims-italian-bot-v2#54]
Hi again, I thought it would be a good to have random cursor speeds between different clicks, for example 
"cursor moved to the nightclub"
"cursor speed set to 5"
"clicked on XX rave"
"speed set to 3"
"clicked buy"

**Comment by grimaldello** [comment]
You want to get the bot going faster when inside rave and slower when outside?

I think that is better to simulate the mouse speed of human movements.

What about instead using a random and possible dynamic speed?

for example a setting like this:

```js
randomNumberOfCoordinatesToSkip: {
                    enabled: true,
                    dynamic: true,
                    min: 4,
                    max: 5
                },
                fixedNumberOfCoordinatesToSkip: 4,
```
- **randomNumberOfCoordinatesToSkip enabled=true and dynamic=true**:
   - the mouse simulator movements will dynamically change its speed while going from one page element to another, based on min and max values
- **randomNumberOfCoordinatesToSkip enabled=true and dynamic=false**:
  - the mouse simulator movements will change the speed at the end of each complete movement from one element to another, based on min and max values
- **randomNumberOfCoordinatesToSkip enabled=false and dynamic=true**:
  - the mouse speed will be fixed and the speed value is the one of the property `fixedNumberOfCoordinatesToSkip`

**Comment by grimaldello** [comment]
Hi @Koles1910.
I don't know, today I was very busy with various things.

No ETA at the moment, but I think by the end of this week I finish it.

**Comment by grimaldello** [comment]
No more developed, since added new wind mouse strategy that simulates also this.
