### ISSUE TITLE
Country Filtering for Hunting

### ISSUE THREAD

**Issue by Fatalitly** [grimaldello/the-crims-italian-bot-v2#67]
I have an important suggestion about usage if bot by the way. I believe it would be very useful if you just could make this update happen. I hope this doesn't take much time for you. I think-regarding bots- the one reason which makes it more possible to get banned is hunting activity. Brazil is the one country which plays this game effectively and dominantly. I think the reports coming about cheating are mostly coming from Brazil. It would be awesome if you could make a filter for hunting function. For example attacking only to Brazillian players. I believe that this will lower the chance of getting banned.

**Comment by grimaldello** [comment]
Hi @Fatalitly,

thank you for the improvement suggestion.

I don't understand if you mean a filter to ATTACK or NOT ATTACK "country specific" players?

For example:
```
attackOnlyPlayersOfCountries: ['BR','IT',...]

or

notAttackPlayersOfCountries: ['BR', 'IT',...]
```

**Comment by grimaldello** [comment]
I'm implementing it.

I decide to add a single property for both cases and I will explain how to use it (with some minor limitations)

**Comment by grimaldello** [comment]
done in release v0.0.26
