### ISSUE TITLE
 Wait to be killed doesn't work

### ISSUE THREAD

**Issue by Fatalitly** [grimaldello/the-crims-italian-bot-v2#72]
Hello,
This feature does not work even though I entered the user name correctly and gives an error as in the screenshot.
I also tried by just typing in the user ID. This time, although he saw the user in the rave, he left without waiting to be killed.

![WhatsApp Image 2023-07-04 at 00 14 16](https://github.com/grimaldello/the-crims-italian-bot-v2/assets/83348930/eff7b07c-10d7-4703-b11d-23ee2f41c73b)

**Comment by Fatalitly** [comment]
There is also another very important issue. The preference for rave or prostitute mansion can be set when using the wait to be killed feature. This choice should be made in such a way that two users can meet more comfortably in the same place.

**Comment by grimaldello** [comment]
> Hello, This feature does not work even though I entered the user name correctly and gives an error as in the screenshot. I also tried by just typing in the user ID. This time, although he saw the user in the rave, he left without waiting to be killed.
> 
> ![WhatsApp Image 2023-07-04 at 00 14 16](https://user-images.githubusercontent.com/83348930/250661890-eff7b07c-10d7-4703-b11d-23ee2f41c73b.jpeg)

Could you paste here how you set the username in the settings of the bot? From that error, I guess there are missing double quotes or single quotes on the usernames in the list.

In your case, it should be:
```
waitToBeKilled: {
    visitorsListAllowedToKill: ["kink"],
    ...
    ...
},
```

**Comment by grimaldello** [comment]
> There is also another very important issue. The preference for rave or prostitute mansion can be set when using the wait to be killed feature. This choice should be made in such a way that two users can meet more comfortably in the same place.

Yes this could be an enhancement.
Please open a new separated issue on github with this improvement.

**Comment by Fatalitly** [comment]
> > Hello, This feature does not work even though I entered the user name correctly and gives an error as in the screenshot. I also tried by just typing in the user ID. This time, although he saw the user in the rave, he left without waiting to be killed.
> > ![WhatsApp Image 2023-07-04 at 00 14 16](https://user-images.githubusercontent.com/83348930/250661890-eff7b07c-10d7-4703-b11d-23ee2f41c73b.jpeg)
> 
> Could you paste here how you set the username in the settings of the bot? From that error, I guess there are missing double quotes or single quotes on the usernames in the list.
> 
> In your case, it should be:
> 
> ```
> waitToBeKilled: {
>     visitorsListAllowedToKill: ["kink"],
>     ...
>     ...
> },
> ```

I'm sorry I missed the quotation marks. Thank you it's ok now
