### ISSUE TITLE
Ability to change hunting speed

### ISSUE THREAD

**Issue by Fatalitly** [grimaldello/the-crims-italian-bot-v2#75]
Actually, I mentioned this before and you said that I can adjust it by changing the bot speed. But when I change the speed of the bot, it also slows down while avoiding other users in Rave. I just want to be able to adjust my speed while killing them so that my escape speed from other users does not change. It hits the user so fast that it's really out of a human use behavior. It is impossible not to be reported at this speed. I think we should be able to set a speed at which we can hit more humanely. It would be great if we could add the option to change the speed while hitting the user without affecting the mouse movement.

**Comment by grimaldello** [comment]
Hi @Fatalitly,

thank you for reporting.

Summarizing, you want a new setting in bot, to set a different speed of the "fake mouse" only for the path from the current position to the "Attack" button?

**Comment by Fatalitly** [comment]
> Hi @Fatalitly,
> 
> thank you for reporting.
> 
> Summarizing, you want a new setting in bot, to set a different speed of the "fake mouse" only for the path from the current position to the "Attack" button?
> 
> Something like:
> 
> ```js
> {
>    mouseSpeedToPressAttackButton: 10,
> }
> ```

I would like the option to set a different speed option for the fake mouse when attacking. A little more humane attack would be good. It would be more realistic to hit it once in a while and not hit it once in a while.

**Comment by grimaldello** [comment]
OK, now the requirement is clear.

Said that, I think it's possible to implement it.
But I need to review some part of the code in order to give you confirmation.

**Comment by zoiodelula** [comment]
Hello, it will be good if we can set a max and a low time to perform a attack, like something between 0.6 to 1.2seconds.

**Comment by grimaldello** [comment]
> Hello, it will be good if we can set a max and a low time to perform a attack, like something between 0.6 to 1.2seconds.

No it's not possible to set a time interval to attack like that.

However, since the total amount of attack depends on where the cursor is placed and where the victim appear in rave, it is surely random and not so different than the time interval you reported.

**Comment by grimaldello** [comment]
Task done.

See last point of: https://github.com/grimaldello/the-crims-italian-bot-v2#hunting in order to understand how to change the speed of the fake cursor while going to press Attack button.
