### ISSUE TITLE
Random Mouse Movements to Generate Logs

### ISSUE THREAD

**Issue by zoiodelula** [grimaldello/the-crims-italian-bot-v2#77]
Its a good idea to have a random movements routines when we are playing, like round circles to the left and right sometimes, just to generate more logs and avoid the bans.

**Comment by grimaldello** [comment]
There is an option for single robbery and gang robbery to enable this.

```js
singleRobbery: {
    makeRandomMovement: true
 },
gangRobbery: {
    makeRandomMovement: true,
    ...
}
```

There is also a random move inside rave before press "Buy" drug button and radius of random movement is defines by this property: `pixelsRadiusOfRandomMovementAroundBuyButton: 100`
